# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo apt-get update -qq
      sudo apt-get install -qq build-essential libopenmpi-dev
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      miniconda.sh -b -p $HOME/miniconda
      export PATH="$HOME/miniconda/bin:$PATH"
      hash -r
      conda config --set always_yes yes --set changeps1 no
      conda update -q conda
      conda install -q -c anaconda python=$TRAVIS_PYTHON_VERSION numpy scipy mpi4py swig
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      export PATH="$HOME/miniconda/bin:$PATH"
      # Configure, make, and install SU2
      CONFIGURE_COMMAND="./preconfigure.py --enable-mpi --with-cc=mpicc --with-cxx=mpicxx --prefix=$TRAVIS_BUILD_DIR --enable-PY_WRAPPER --disable-tecio"./bootstrap
      autoreconf -f -i
      $CONFIGURE_COMMAND
      make -j 4
      make install    
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Get the test cases
      git clone -b develop https://github.com/su2code/TestCases.git ./TestData
      cp -R ./TestData/* ./TestCases/
       # Get the tutorial cases
      git clone -b develop https://github.com/su2code/su2code.github.io ./Tutorials
         
      export SU2_RUN=$PWD/bin
      export SU2_HOME=$PWD
      export PATH=$PATH:$SU2_RUN
      export PYTHONPATH=$PYTHONPATH:$SU2_RUN
       
      # Enter the SU2/TestCases/ directory, which is now ready to run
      cd TestCases/
      
      python parallel_regression.py
  
